// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyqTOI_b_CwvnCsdWDtrGS6K6ZZ0evmdY',
    appId: '1:370221978459:web:28bed4fbeac1ec3d1ac07e',
    messagingSenderId: '370221978459',
    projectId: 'csen268-f25-g3',
    authDomain: 'csen268-f25-g3.firebaseapp.com',
    storageBucket: 'csen268-f25-g3.firebasestorage.app',
    measurementId: 'G-MKBL6JPMC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWD3c0cEwp3dIvUX5JOvaLB2a7bOy3Q4',
    appId: '1:370221978459:android:cb80ab15247e5e711ac07e',
    messagingSenderId: '370221978459',
    projectId: 'csen268-f25-g3',
    storageBucket: 'csen268-f25-g3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7uqQ0IXxBhKL8Inuk3HZ0N63lJFfxwg',
    appId: '1:370221978459:ios:6735d85c74f258621ac07e',
    messagingSenderId: '370221978459',
    projectId: 'csen268-f25-g3',
    storageBucket: 'csen268-f25-g3.firebasestorage.app',
    iosBundleId: 'com.csen268.f25.g3',
  );
}